### ISSUE TITLE
XCR Roadmap 1: Widgets

### ISSUE THREAD

**Issue by skunktober** [beachweak/XCR#1]
XCR will be divided up into specific "roadmaps" for its progress since the platform is so vast. This roadmap covers the goals towards a complete and integrated widgets system.

- [x] Widgets can be imported via their JS, CSS & HTML files
- [x] Widgets are loaded into XCR via JSON
- [x] Widget selection GUI exists
- [x] Allow for deletion of widgets
- [x] Fix formatting of widgets to limit two per row
- [x] Add widget saving for when XCR is closed
- [x] Fix mismatched deletion orders
- [x] Fix issue of conflicting CSS code breaking other widgets
- [x] Finish porting RC2 widgets to XCR 
- [x] Port RC2 code into individual unique (IU) XCR code
- [x] Style widget delete button and integrate into title bar
- [x] Review IU Widgets and see if they work across platforms
- [x] Final cleanup

**Comment by skunktober** [comment]
Current prevalent issues are that widgets sometimes do not delete in order, and that CSS can conflict with other widgets (like calculator and todo list). Later today (hopefully) widgets will be moved over to an individual naming basis, making their CSS unique through the use of a specialised ID

**Comment by skunktober** [comment]
After re-scripting parts of the protocol for adding widgets, widgets now have an auto-generated UUID added to widgetConfigs.json. This fixes the issue of widgets being deleted out of order. 

CSS conflicts have been easily fixed by giving shared CSS individual names. In our context, Todo List and Calculator no longer use .widget-content, but rather .todo-widget-content and .calculator-widget-content respectively. Creation of new widgets should do this as well.

**Comment by skunktober** [comment]
XCR 1.0.0-RELEASE will be available soon!
