### ISSUE TITLE
XCR Roadmap 2: Apps

### ISSUE THREAD

**Issue by skunktober** [beachweak/XCR#2]
XCR will be divided up into specific "roadmaps" for its progress since the platform is so vast. This roadmap covers the goals towards a functioning apps system. 

- [x] Create apps page
- [x] Create way to submit apps
- [x] Create way to set title and link
- [x] Create logic for automatically grabbing favicon
- [x] Create logic for automatically grabbing site title if not given
- [x] Format app list
- [x] Final cleanup

**Comment by skunktober** [comment]
XCR 1.0.0-RELEASE will be available soon!
