### ISSUE TITLE
XCR Roadmap 3: Customisation

### ISSUE THREAD

**Issue by skunktober** [beachweak/XCR#3]
XCR will be divided up into specific "roadmaps" for its progress since the platform is so vast. This roadmap covers the progress towards a fully integrated profile customisation system.

- [x] Create customisation page
- [x] Enable custom profile pictures
- [x] Enable custom name changer
- [x] Enable custom background changer
- [x] Enable colouring of banner and navigation bar
- [x] Enable colouring of buttons
- [x] Enable data import and export
- [x] Allow for user to clear data
- [x] Final cleanup

**Comment by skunktober** [comment]
XCR 1.0.0-RELEASE will be available soon!
