### ISSUE TITLE
XCR Roadmap 4: Misc

### ISSUE THREAD

**Issue by skunktober** [beachweak/XCR#4]
XCR will be divided up into specific "roadmaps" for its progress since the platform is so vast. This roadmap covers misc changes to the platform, including design and other logic.

- [x] Final pass on art design
- [x] Change name from "Electron" to "XCR" in finished package
- [x] Amend XCR logo to be in accordance with MacOS desktop icon standards
- [x] Make sure app runs well
- [x] Change styling on various elements
- [x] Package for Apple Silicon Macs (ARM64)
- [x] Package for Intel-based Macs (x86_64)
- [x] Package for Windows (x64)

**Comment by skunktober** [comment]
XCR 1.0.0-RELEASE will be available soon!
